### ISSUE TITLE
Bumblebee Camera Issues

### ISSUE THREAD

**Issue by boris-g** [Hoektronics/bumblebee#2]
Python log:

Traceback (most recent call last):
  File "bumblebee.py", line 367, in <module>
    bee.main()
  File "bumblebee.py", line 180, in main
    curses.wrapper(self.mainMenu)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "bumblebee.py", line 211, in mainMenu
    self.getBots()
  File "bumblebee.py", line 110, in getBots
    self.scanDevices()
  File "bumblebee.py", line 88, in scanDevices
    data['cameras'] = camera_control.scanCameras()
  File "/home/pi/bumblebee/bumblebee/camera_control.py", line 141, in scanCameras
    **scanCameraRaspi(cameras)
  File "/home/pi/bumblebee/bumblebee/camera_control.py", line 96, in __scanCameraRaspi
    with picamera.PiCamera() as camera:
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 324, in __init**
    self._init_camera()
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 360, in _init_camera
    "Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

**Comment by Jnesselr** [comment]
Just an update on this. I now have a Raspi camera, so I'll be able to test this relatively soon.
