### ISSUE TITLE
Loading Replicator 2 (Clone) failed

### ISSUE THREAD

**Issue by beniroquai** [Hoektronics/bumblebee#6]
Hi. I installed it a second time to give it a try. This time it's just not loading the Makerobt on the pi. 

Log info gives me the following:

[2015-02-02 08:16:45,534] INFO: Started up, loading bot list.
[2015-02-02 08:16:45,534] INFO: Started up, loading bot list.
[2015-02-02 08:16:45,588] INFO: Downloading Printrun from https://github.com/kliment$
[2015-02-02 08:17:11,702] INFO: Downloading Printrun finished
[2015-02-02 08:19:15,272] ERROR: devicescanresults call failed: internet connection $
[2015-02-02 08:23:31,894] INFO: Creating worker thread for bot Replicator
[2015-02-02 08:23:31,906] INFO: Loading bot Replicator
[2015-02-02 08:23:31,931] INFO: Downloading s3g from https://github.com/makerbot/s3g$
[2015-02-02 08:23:35,767] INFO: Downloading s3g finished
[2015-02-02 08:23:35,765] INFO: Shutting down.
[2015-02-02 08:23:35,792] ERROR: Replicator: Please use Makerbot's version of pyseri$
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/workerbee.py", line 87, in $
    self.driver = self.driverFactory()
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/workerbee.py", line 98, in $
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/drivers/s3gdriver.py", line$
    raise Exception("Please use Makerbot's version of pyserial")
Exception: Please use Makerbot's version of pyserial
[2015-02-02 08:23:35,799] ERROR: Replicator: Error mode: Please use Makerbot's versi$
[2015-02-02 08:23:35,804] INFO: Replicator: Setting bot status as error.
[2015-02-02 08:23:37,535] INFO: Replicator: Shutting down.
[2015-02-02 08:23:37,551] INFO: Replicator: Bot startup
[2015-02-02 08:26:30,286] INFO: Started up, loading bot list.
[2015-02-02 08:26:32,123] INFO: Creating worker thread for bot Replicator
[2015-02-02 08:26:32,143] INFO: Loading bot Replicator
[2015-02-02 08:26:32,177] INFO: Downloading s3g from https://github.com/makerbot/s3g$
[2015-02-02 08:27:08,012] INFO: Downloading s3g finished

Is there a problem with intenet? I followed your tutorial step by step. Great project by the way! :)

**Comment by Jnesselr** [comment]
Correct, MakerBot requires you to use their own special little version of
pyserial. You can install it from github.com/makerbot/pyserial by running
"python setup.py install" in that directory. You may have to uninstall the
original pyserial, but I doubt it.

**Comment by beniroquai** [comment]
Ok. I'm back. I tried again (new installation, perhaps some server went down because of the new pi?!)
Now I get the following message:

Error This bot is offline with the following error: Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/bumblebee/workerbee.py", line 262, in processJob self.driver.startPrint(self.jobFile) File "/usr/local/lib/python2.7/dist-packages/bumblebee/drivers/s3gdriver.py", line 50, in startPrint raise ex Exception: could not open port : [Errno 2] No such file or directory: '' 

Do I just need to install the drivers like this:


$ apt-get remove python-serial

$ git clone https://github.com/makerbot/pyserial.git pyserial
$ cd pyserial
$ python setup.py install

$ cd ..
$ git clone https://github.com/makerbot/s3g.git makerbot 
$ cd makerbot
$ python setup.py install

Or what am Im supposed to do?

**Comment by Jnesselr** [comment]
Can you paste the output of 'pip freeze' for me? Oh, and you don't have to install the s3g repo at all, just the pyserial one. So pretty much just up until the 'cd ..' command. It also doesn't matter where it's installed, just that 'pip freeze' shows that you have the makerbot version of pyserial installed.

As for the error, I'd need to know what the command 'ls /dev/tty*' showed, and what was listed in the bot configuration.

I really would like to change this so pyserial for makerbot is automatically included, but I don't have the setup to test that. I will, one day, just not yet. You'd be able to test it, it just requires a non makerbot printer and a makerbot based one. The issue is that I don't know if unloading the original pyserial library and then reloading the new one will mess up the connection of the original library. Actually, I have an idea to test that.

**Comment by beniroquai** [comment]
Hi, at first the output of freeze:


pi@raspberrypi ~ $ pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
Pygments==2.0.2
RPi.GPIO==0.5.8
argparse==1.2.1
beautifulsoup4==4.3.2
bqclient==0.5.3
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
mcpi==0.1.1
numpy==1.6.2
picamera==1.9
pifacecommon==4.0.0
pifacedigitalio==3.0.4
pygame==1.9.1release
pygobject==3.8.2
pyserial==2.5
requests==2.5.1
requests-oauth==0.4.1
wsgiref==0.1.2

Output of  ls /dev/tty after installing the driver and connecting everything
pi@raspberrypi ~ $ ls /dev/tty
/dev/tty


What else do you need? Can I help you with any outputfiles?
When enterring sudo bumblebee I get the same output:

BotQueue v0.5.3
Time: Tue Feb  3 07:39:01 2015

    ID              BOT NAME      STATUS  PROGRESS    JOB ID      STATUS
   XXX              Makerbot       error  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/workerbee.py", line 262
, in processJob
    self.driver.startPrint(self.jobFile)
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/drivers/s3gdriver.py",
line 50, in startPrint
    raise ex
Exception: could not open port : [Errno 2] No such file or directory: ''


q = quit program

Network Status: ONLINE | Net Errors: 0

**Comment by Jnesselr** [comment]
There needs to be the asterisk after the tty in 'ls /dev/tty*'. Right now, bumblebee should never be installed with root nor run with root if you're using the auto updating 'bqclient'.

Hmm... Let me cheat to speed up the process... Okay, I see the device name is '/dev/ttyACM0'. I went ahead and edited the bot to have the correct port. That actually brings up a bug I should fix. Basically, you need to click the drop down arrow and select a port (Under editing a bot > Driver Configuration > Serial Port). The client shouldn't be willing to let you grab jobs without it.

For now though, it works. Be sure to give it a go. Also, I haven't fully figured out exactly how to run bumblebee with root privileges mixed in. Basically, if you install it with root, run it with root. I just don't want to have an error that accidentally deletes a lot of data.

**Comment by beniroquai** [comment]
Ok. Thank you. So did you manage to find the correct port from remote? :D Crazy.
Anyway. Is this "just" a work arround or will it work everytime I'm setting up a new pi? Can I provide any information about the makerbot? Logs?

bumblebee shouldn't run as root, right? So, it should be better to install as non root? Although I exactly followed all the instructions I'm getting this error when running as non-root:


pi@raspberrypi ~ $ bumblebee
Traceback (most recent call last):
  File "/usr/local/bin/bumblebee", line 9, in <module>
    load_entry_point('bqclient==0.5.3', 'console_scripts', 'bumblebee')()
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/__main__.py", line 17, in main
    main()
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/app.py", line 402, in main
    bee = BumbleBee()
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/app.py", line 42, in __init__
    hive.loadLogger()
  File "/usr/local/lib/python2.7/dist-packages/bumblebee/hive.py", line 243, in loadLogger
    fh = logging.handlers.RotatingFileHandler(log_file, maxBytes=26214400, backupCount = 3)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 924, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/bumblebee/info.log'


Thank you! :)

**Comment by beniroquai** [comment]
Ok. Now, there are no errors, but nothings happening either ;)


Time: Tue Feb  3 08:41:11 2015

    ID              BOT NAME      STATUS  PROGRESS    JOB ID      STATUS
   XXX              Makerbot     working     0.00%      XXXX taken

q = quit program

Network Status: ONLINE | Net Errors: 0

**Comment by Jnesselr** [comment]
Well, definitely calling it with root caused some problems. Hmm. Have you used virtualenv before? I'm trying to figure out the best way to handle issues like this because it's permission based. I guess you're running it for root now, which is alright. I wouldn't suggest it, but you might need to uninstall bqclient as root and reinstall it without it to fix that.

As far as the reason progress is 0%, I'd need to see the log. It might be another permissions issue, I don't know. Can you upload the entire file?

**Comment by jamesarm97** [comment]
I basically tried the same thing last night before reading this. Got to the point where I used the makerbot github and got past the driver errors and actually queued up a job. The printer showed the status screen with Botqueue job     %-- and showed the current temperatures but nothing after that, no homing, temperature changes or attempts to print. Seems it is kind of talking but not printing. Also had to run as root for same reason with the above comments.

**Comment by Jnesselr** [comment]
This should be fixed in the latest version. I finally have access to a Makerbot based printer.
